version: '3.8'

services: 
  db: 
    image: 'postgres:15.0-alpine'
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: remix-experiment
    ports: 
      - '5435:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data